// Cafes
export const FETCH_CAFES_REQUEST = 'FETCH_CAFES_REQUEST';
export const FETCH_CAFES_SUCCESS = 'FETCH_CAFES_SUCCESS';
export const FETCH_CAFES_FAILURE = 'FETCH_CAFES_FAILURE';

export const ADD_CAFE_REQUEST = 'ADD_CAFE_REQUEST';
export const ADD_CAFE_SUCCESS = 'ADD_CAFE_SUCCESS';
export const ADD_CAFE_FAILURE = 'ADD_CAFE_FAILURE';

export const EDIT_CAFE_REQUEST = 'EDIT_CAFE_REQUEST';
export const EDIT_CAFE_SUCCESS = 'EDIT_CAFE_SUCCESS';
export const EDIT_CAFE_FAILURE = 'EDIT_CAFE_FAILURE';

export const DELETE_CAFE_REQUEST = 'DELETE_CAFE_REQUEST';
export const DELETE_CAFE_SUCCESS = 'DELETE_CAFE_SUCCESS';
export const DELETE_CAFE_FAILURE = 'DELETE_CAFE_FAILURE';

// Employees
export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';

export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

export const EDIT_EMPLOYEE_REQUEST = 'EDIT_EMPLOYEE_REQUEST';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_FAILURE = 'EDIT_EMPLOYEE_FAILURE';

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAILURE = 'DELETE_EMPLOYEE_FAILURE';
